[GLOBAL]
pants_version = "2.29.0"

pants_ignore = [
]

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.isort",
  "pants.backend.experimental.python.lint.ruff.check",
  "pants.backend.experimental.python.lint.ruff.format",
  "pants.backend.python.typecheck.mypy",
]

[source]
root_patterns = ["/"]

[python]
enable_resolves = true
interpreter_constraints = ["CPython>=3.13"]
pip_version = "latest"

[python.resolves]
python-default = "3rdparty/lockfiles/default.lock"
python-linux-cpu = "3rdparty/lockfiles/linux_cpu.lock"
python-linux-gpu = "3rdparty/lockfiles/linux_gpu.lock"
python-macos-cpu = "3rdparty/lockfiles/macos_cpu.lock"

[generate-lockfiles]
diff = true
